### PR TITLE
Add a word list filter

### LINKED ISSUE #70: Add a word list filter
Please add a `string List` property to the `Entry` class in the back-end/API. The property will indicate which list this word belongs to, zalizniak.txt or names.txt:

* "нарицательные" (common words) - zalizniak.txt
* "собственные" (proper names) - names.txt

Add a query string parameter called `list` to the API that filters returned entries by the list provided, e.g.

    http://api.gramdict.ru/v1/search/*?list=common&list=proper

Specifying all available lists like above will have the effect of specifying none. A bit counter-intuitive, but consistent with the symbol filter.

Then add a filter group to the search bar:

image

None of the options will be selected by default (unlike in the mock-up above where both are selected).

### PR DESCRIPTION
**Pull request by Meberem**
Closes #70, uses word lists from other PR, query string parameters are created in the same way as the filter and lists are preserved between page loads/navigations just like the other parameters

image.

Sorry for the lack of communication been having some fun with EasyJet today...

### CODE REVIEW

**Comment by bzaar** [comment]
Thanks! Could you add a horizontal scroll bar to the filters? So that the height of the filters area is more or less the same?

image

And `whitespace: nowrap` for "мн. одуш" and the rest please. Otherwise they get wrapped on the phone. Thanks!

**Comment by bzaar** [comment]
Or perhaps not a scroll bar but some sort of a carousel control? https://react-bootstrap.github.io/components/carousel/

**Comment by Meberem** [comment]
I allowed the area to scroll, this looks quite nice on a mobile device. Adding the carousel might cause some issues as on some devices a slide might have to be scrollable to keep the content visible. We'd also have to add bootstrap to the project which would be nice not to have to do

File 21-05-2019, 21 09 47

**Comment by bzaar** [comment]
Thanks! The scrolling looks good. 

Can the new filters have the same font size and baseline as the rest?

image

**Comment by bzaar** [comment]
The clickable area of the new filters is much wider than necessary. E.g. clicking on the  far right as shown below will trigger the filter:

image

**Comment by bzaar** [comment]
The scroll bar is keeping the entry counts from wrapping around onto a new line like they used to. I would rather keep them visible at all times like before. I think this can be achieved by moving the entry counts outside the scrollable area and allowing the counts to be either on the right of the scrollable filter area (space permitting) or wrap around onto the next line.

**Comment by Meberem** [comment]
Ok I think that push should do it

**Comment by bzaar** [comment]
Thanks! Almost it. Could "собственные" and "нарицательные" be moved into the scrollable area?

**Comment by Meberem** [comment]
Sorry my bad, I misread one of those comments, should be good now

**Comment by bzaar** [comment]
Perfect, thanks!

**Pull request merged**
