### PR TITLE
Set css variable when filters open/close for page offset

### LINKED ISSUE #95: Fix filter pane positioning
Currently, when the filter pane is expanded, the search results are pushed down so that the first results are visible:

image

However, if you copy and open the same URL (http://dev.gramdict.ru/search/*?symbol=%D1%81%D0%B2) in a new browser tab, the filter pane hides the results:

image

Which is undesirable. The results should be pushed down as well.

The 'push-down' behaviour is implemented by [this script](https://github.com/morpher-ru/gramdict/pull/94/files#diff-8447f5d27fdbc1ed81646f6006f8cd2fR55). Ideally, I would like this done using only CSS and no javascript.

Please submit a PR on top of the https://github.com/morpher-ru/gramdict/tree/dvacom-design-update branch.

Also, please keep in mind this future task: #93.

### PR DESCRIPTION
**Pull request by Meberem**
Closes #95. 
- Listens to a change of filters being open
- grabs the height of filters if possible
- set the height as a css varaible
- tweak the page offset to include the css variable.

Unfortunatley the achor-offset property is highly experimental so some JS is still needed to do this

### CODE REVIEW

**Comment by bzaar** [comment]
Hi Matt, thanks for this update. Unfortunately, I don't see the search results being pushed down when the filters open as detailed in #95.

https://photos.app.goo.gl/pQGsYqvbkKrvaFzx5

**Comment by bzaar** [comment]
Also, we have this working in master without any JS.

**Comment by Meberem** [comment]
I haven't deployed it anywhere, it is working locally. Would you like it deployed?
As far as I can tell that is not the case, see setSearchBarHeight();
The only way to do this without js would be to use flex box and then the results would never appear "under" filters pop out, would that be ok?

**Comment by bzaar** [comment]
I deployed it to dev.gramdict.ru and tested it with my phone. I have now tested it on a PC and it worked perfectly. So it must be just my old phone.

Could you get it to work on my phone too? I'll attach version info shortly.

**Comment by bzaar** [comment]
Version info: https://photos.app.goo.gl/UHE14c7yhAx1bkR7A

**Comment by bzaar** [comment]
And yes, feel free to deploy any updates to dev.gramdict.ru. Thanks.

**Comment by bzaar** [comment]
Please use AppVeyor for deployment: https://ci.appveyor.com/project/morpher/gramdict/deployments

**Comment by Meberem** [comment]
Cool, just to clarify: Did you want it so that the results will *never* appear under the filter box, so that we do not need to use javascript to set the offset? 
Or do you want it to function as is but working on chrome for mobile?

**Comment by bzaar** [comment]
That's a good question. I can see the filter bar getting wider in the
future to accommodate more filters until it eventually takes up the whole
width of a PC screen. Then there won't be much difference between the two
approaches. So I vote for the simpler, no-JS approach. Thanks!

**Comment by bzaar** [comment]
Sorry it is just me or did we lose the ability to scroll results entirely? Deployed to http://dev.gramdict.ru/search/*?symbol=%D0%BC%D0%BE

**Comment by Meberem** [comment]
So I'm not quite sure why these bits didn't make it into my first commit but scrolling should be working again with this one

**Comment by bzaar** [comment]
Thanks! There is now an extra margin on the right hand side:
https://photos.app.goo.gl/NuPgQ6kVfv1VgqQm8

**Comment by bzaar** [comment]
And if you could make the rhs margin of the text box smaller and more in
line with the other margins, would be fab!

**Comment by bzaar** [comment]
(That one was there before)

**Comment by Meberem** [comment]
I think those last commits should do it

**Comment by bzaar** [comment]
Thanks, that does it! However, I found that the infinite scroll component gets stuck sometimes:

image

I remember we had this problem before and then you fixed it. Can you fix it again?

**Comment by bzaar** [comment]
I had to scroll down a few pages before I hit this bug. I can’t recreate it on gramdict.ru which has this PR’s base branch on it.

**Comment by Meberem** [comment]
Hi sorry been a busy few days, I’ll be able to take a proper look at it on Monday if that’s alright

**Comment by Meberem** [comment]
I have taken another look at the setup and everything appears to be fine and I cannot replicate it, all rather annoying. Could you take a look at the JS console when this happens to see if there is any diagnostic info there?
I have bumped the scroll threashold to load slightly "earlier" on the page, which should mitigate any js maths madness with calculating the scroll position

**Comment by bzaar** [comment]
After a bit more testing, I 've found that the bug occurs at the zoom level of 125% (Ctrl-+ twice in Chrome). 

image

It does not occur in the base branch:

image

As soon as I set the zoom level to 100% (Ctrl-0 in Chrome), the scrolling works again (in this PR).

Can it be made to work at any zoom level?

**Comment by Meberem** [comment]
Just to further complicate matters, my chrome on 125% is fine on the two machines and resolutions I have tested.
image

Does CTRL + SHIFT + R help at all?

**Comment by bzaar** [comment]
Yes, it does, it did help. Sorry for messing about for so long. it should have been the first thing I tried. PR accepted.

**Comment by Meberem** [comment]
Don't sweat it, happens daily to me I swear

**Pull request merged**
