### PR TITLE
Tooltip issues

### LINKED ISSUE #62: Tooltip issues
There are tooltips on the filter bar which have a few issues:

1. They are getting in the way of normal operation when you are trying to select/deselect filters. Perhaps adding a delay before a tooltip appears would help alleviate this.
2. It’s hard to click the link inside the tooltip. Perhaps adding a delay before a tooltip disappears would help alleviate this. Also would be nice if the tooltip didn’t move with the mouse.
3. There’s too much margin around the tooltip.
4. The background should be fully opaque.
5. The tooltips are also transparent to clicks, i.e. you can click the filters underneath the tooltips. Not sure it’s a good idea. I’d like that removed.

Overall, I want the tooltips to be less intrusive and easy to use.

### PR DESCRIPTION
**Pull request by Meberem**
This should Close #62, I believe all the points have been addresses but could you let me know if the show/hide delays are too much/too little?

### CODE REVIEW

**Comment by bzaar** [comment]
Thanks, that looks better. Still,

* Clicking the link in the tooltip is next to impossible as the tooltip keeps "running away" from the mouse cursor. See also point 2 in #62.
* _Some_ margin (0.5rem?) on the sides would look better IMHO.

**Comment by Meberem** [comment]
This is the result on my machine:
image

The tooltip is static and doesn't move with the mouse and there is still some padding around the edge.

What are you seeing? Is it possible to deploy this build to an environment to see if this is just my machine causing issues?

**Comment by bzaar** [comment]
I have [deployed](https://ci.appveyor.com/project/morpher/gramdict/deployment/2107715) 1.0.37 to dev.gramdict.ru and this is what I see:

image

The tooltips are moving with the mouse. Did Ctrl-F5 as well.

**Comment by Meberem** [comment]
Scripts weren't being rebuild :o I have made a change to the appveyor.yml that should accomplish this. Can you retry now
image

**Comment by bzaar** [comment]
Perfect, thanks!

**Pull request merged**
