### PR TITLE
Use the full window width in search mode

### PR DESCRIPTION
**Pull request by Meberem**
I think this addresses issue #18, please let me know if there is anything else

### CODE REVIEW

**Comment by bzaar** [comment]
Thanks! Can it do more than two columns?

**Comment by Meberem** [comment]
Oh yes. Sorry not at my pc atm, but on my monitor it was just shy of 4 columns

**Comment by Meberem** [comment]
image

**Comment by bzaar** [comment]
Thank you! Let me get to my pc and get some taste of the new layout.

**Comment by bzaar** [comment]
I have just accidentally discovered that the menu bar disappears when I follow this link:

http://gramdict.ru/declension/symbols#standart1

It's probably nothing to do with this change. Still, can you have a look?

**Comment by bzaar** [comment]
It won't go wider than 6 columns for some reason. Can we try and fit as many columns as possible?

image

**Comment by bzaar** [comment]
Otherwise looks good!

**Comment by Meberem** [comment]
This is on the page with the menu bar missing now
image

**Comment by bzaar** [comment]
Thank you!

**Pull request merged**
