### PR TITLE
initial loading work

### PR DESCRIPTION
**Pull request by Meberem**
I went with a Google inspired loader, please see this screenshot:
loading

This screenshot demonstrates what happens when an error occurs
image

The infinity scroll should only load one set at a time, so I am not sure how `But infinity scroll should be disabled while the progress bar is visible.` affects this. 

Please let me know if you have any questions,

Kind regards,
Matt

### CODE REVIEW

**Comment by bzaar** [comment]
Very lively colours, thanks! :)  

As far as I can see, infinity scroll *is* disabled when the red bar is visible, i.e. it doesn't even try to load more results when I scroll down which is exactly what I wanted.

There is one scenario though where it does not behave quite like I want it to:
* Open /contents. Click inside the search box. Wait for the results to arrive.
* Disconnect from the internet.
* Scroll all the way down. The red bar will appear.
* Type "а" into the search box.
* Connect to the internet.
* Click retry.

It fetches the first page again (starting with "а") and adds it to the existing page:

image

It should have deleted the old results because it's a new search.

I hope that will be easy to fix!

**Comment by Meberem** [comment]
This should fix it

**Comment by bzaar** [comment]
Yes, that fixes it. But it also seems to break infinity scroll: If you repeat the steps above and then scroll all the way down, it is not loading the next page (despite it saying "Loading..."):

image

And while you're at it, can "Load more..." be centred? Thanks.

**Comment by Meberem** [comment]
This was a tricky one to track down. This should fix it until a patch I sumbitted to the InfinityScrollComponent is merged

**Comment by bzaar** [comment]
Thanks! I'll have a look and later today and let you know.

As a side note, my first shot at Typescript didn't go very well:

&lt;div className=&quot;lemma&quot; style=&quot;text-align: {r.lemma.startsWith('*') ? 'right' : 'left'}&quot;&gt;{r.lemma}&lt;/div&gt;

I think I need to read a primer first.

**Comment by bzaar** [comment]
Great work again and thanks for the extra effort! Merged.

**Pull request merged**
