### PR TITLE
Put table of contents in to an accordion control

### PR DESCRIPTION
**Pull request by Meberem**
This was a bit more involved than I initially thought but here it is, using the library you liked before. The main issue was getting the content into the format the library expects, I have moved the old contents page to staticContents which has a function to turn the HTML into react components. This was so it was possible to experiment with the library and easily add to the contents at a later time if needed.

Please let me know what you think of the styling, screenshot below

image
image

### CODE REVIEW

**Comment by bzaar** [comment]
Great, thanks! Any chance we could get "find on page" to work? It seems to work fine on the control's demo page.

**Comment by bzaar** [comment]
Would be nice to make the line spacing smaller:

image

And align all same-level headings on the same vertical. Currently, headings with a > marker are a bit more "in" than the rest.

**Comment by Meberem** [comment]
I had adjusted the padding so the line height should be better and the items should be aligned vertially correctly now.

I am having trouble with the "find on page", I am using https://springload.github.io/react-accessible-accordion/ as the demo page and in chrome I cannot get it to find the the contents `do adipisicing` unless the last item is expanded
image
image
Am I doing something different to you?

**Comment by Meberem** [comment]
Furthermore [this issue](https://github.com/springload/react-accessible-accordion/issues/211#event-2377458045) I raised seems to suggest that such a thing is impossible at the moment

**Comment by bzaar** [comment]
Unfortunately, I won't be able to merge this as I use Ctrl-F a lot and losing this is quite a deal breaker for me. Thanks for your efforts and for raising an issue with the accordion control devs.

**Pull request closed without merging**
