### PR TITLE
Fix permalink target paragraph is hidden behind the menu bar (#120)

### PR DESCRIPTION
**Pull request by Ivannnnn**

### CODE REVIEW

**Comment by bzaar** [comment]
Thanks. Could you resolve the conflicts in this branch? And please provide a title for the PR.

**Comment by bzaar** [comment]
Thanks. Is this PR ready for a review?

**Comment by bzaar** [comment]
If afraid the indentation of list items will have to stay as it was. Could you also remove the whitespace-only differences? TIA.

**Comment by Ivannnnn** [comment]
Probably not possible then with CSS alone. Am I allowed to change the HTML slightly?

**Comment by bzaar** [comment]
Well, if you update ALL similar bits of HTML so these numbered paragraphs
all look the same, then that could be an acceptable solution.

**Comment by bzaar** [comment]
Thanks, it works fine now: http://dev.gramdict.ru/howtouse#digits

Can you remove all the whitespace-only differences in the [diff ](https://github.com/morpher-ru/gramdict/pull/121/files)? They are causing conflicts with master.

**Comment by Ivannnnn** [comment]
This PR should be irrelevant.

**Comment by bzaar** [comment]
Well I can't accept this PR as long as it has conflicts.

**Comment by Ivannnnn** [comment]
I can't make any changes, that fork is gone. Maybe remove this one commit and accept the other PR. There will be a small conflict in the CSS which I can easily resolve.

**Pull request closed without merging**
