### PR TITLE
use history api to persist and load search terms

### LINKED ISSUE #36: Search links
Allow users to copy a link to / bookmark the current search page. For that to work, update the URL in the browser each time the search term or filters change or when the user clicks the search box for the first time:

http://gramdict.ru/search/*?symbol=мо

When a link like that is pasted in the browser, the website should initialize the filters and the search term from the URL and forward the query string to the API, adding pagesize and pagenum. Then display the search results as usual.

### PR DESCRIPTION
**Pull request by Meberem**
Should resolve #36. This is more of a behavioural one but screenshot shows the new URL
image

### CODE REVIEW

**Comment by bzaar** [comment]
Thank you! Can you push to live please?

**Comment by Meberem** [comment]
I've just done that, and pushed a new web.config to allow * in the url

**Comment by bzaar** [comment]
Thanks. I see the URL being updated but I don't see the filters being
updated from the URL when its pasted into the browser.

**Comment by Meberem** [comment]
I've expanded the filters section, here is what it looks like on mine after I've entered http://www.gramdict.ru/search/*?symbol=%D1%81%D0%B2
image

**Comment by bzaar** [comment]
That seems to work now, not sure why it didn't before.

I get an api error when opening this url:

http://gramdict.ru/search/ок?symbol=нсв,мо

**Comment by Meberem** [comment]
I've pushed/deployed a fix

**Comment by bzaar** [comment]
Thank you! That fixed it. Another test case:

* Go to http://gramdict.ru/search/
* Tap the first filter.

The URL becomes

http://gramdict.ru/search/*?symbol=,м

Ideally it should be :

http://gramdict.ru/search/*?symbol=м

(no comma)

**Comment by Meberem** [comment]
I thought I had posted this when I pushed the commit but I forgot sorry. This should be fixed in the latest pushed and deployed version

**Comment by bzaar** [comment]
Thank you. 

This one seems to be specific to Samsung Internet browswer:

* Go to http://gramdict.ru/search/*?symbol=част.,предик.
* Wait for the results to load.

Note that the dot at the end of the URL is gone and "предик."  is not selected. 

It works fine in Chrome (Windows and Android).

If you can't think of a quick fix, let's just leave it.

**Comment by Meberem** [comment]
It looks like that URL is missing the last dot, can you try [http://gramdict.ru/search/*?symbol=част.,предик.](http://gramdict.ru/search/*?symbol=част.,предик.) and see if that fixes it?

**Pull request merged**
