### PR TITLE
Hide the filters panel when user scrolls down

### LINKED ISSUE #93: Hide the filters panel when user scrolls down
When the user starts scrolling down the search results, the filters panel should scroll away with the results.

If the scrolling stops while the panel is still partially visible, the panel should finish collapsing with a short animation.

Scrolling up will **not** bring the panel back into view.

### PR DESCRIPTION
**Pull request by Meberem**
Closes #93

### CODE REVIEW

**Comment by bzaar** [comment]
Thank you! It essentially does what's required but is a bit rough on the edges. E.g. I managed to scroll away the search bar which shouldn't happen: https://photos.app.goo.gl/EsYCGAyfZXARgVRq7

**Comment by bzaar** [comment]
Also, if you open the search page, scroll down, open the filters and then scroll up, the filters detach from the top and then jump back up which doesnt look pretty.

**Comment by bzaar** [comment]
I'd like only the height of the filter pane to change, not the position.

**Comment by bzaar** [comment]
The filters now open with an animation - thats a nice touch!

**Comment by Meberem** [comment]
I think there are a number of things Chrome does on mobile for performance/battery life which prevent some of the ideas I had from working. I have tweaked it slightly now to rely more heavily on css, can you give that build a try?

**Comment by bzaar** [comment]
The jumping about is fixed, thank you! Two points remain:

1. I was still able to get it to hide the search bar as in my first message on this thread. This should not be possible. I don't have a definitive repro but I started by first scrolling down, then opening the filters and then scrolling up and down randomly. This happens on the phone only.
2. I'd like to narrow the definition of "when the user finishes scrolling". Currently, it seems to be "when the search results stop moving up" while I'd like it to be "when the user lift their finger up", either away from the screen or the mouse button. While the finger is down, the filters panel should collapse/expand with the scrolling (but no taller than its normal height of course). Would that be possible? The current approach will work when using the keyboard or the mouse scrolling wheel for scrolling.

**Comment by Meberem** [comment]
1. I don't quite fully understand why this is allowed to happen, but I think I have replicated it and fixed it
2. I think the latest should acomplish what you want

**Comment by bzaar** [comment]
Hi Matt, thanks for this update. A few comments:

1. There is something wrong with scrolling on non-search pages e.g. http://gramdict.ru/contents. There's no scroll bar and touch scrolling doesn't work.

2. Try this:

* Open the filters and scroll down until the filters are half visible.
* Scroll up a bit.

   Observed behaviour: the filters jump into the fully expanded state.
   Desired behaviour: the filters scroll up (or down) with the page until the finger is up.

Ideally, there should be as little "jumping" as possible.

3. Open the filters and swipe the page up (i.e. scroll down).

   Observed behaviour: the page stops moving and then scrolls down a couple of lines.
   Desired behaviour: the page stops moving (normal scrolling behaviour).

Many thanks, Sergey

**Comment by bzaar** [comment]
Perfect! 

Well, nearly... the right margin of the text box got wider for some reason?

image

**Comment by bzaar** [comment]
One more thing: this link automatically shows the filters bar:

http://gramdict.ru/search/*?symbol=%D0%BC%D0%BD.

While this doesn't:

http://dev.gramdict.ru/search/*?symbol=%D0%BC%D0%BD.

It should.

**Comment by bzaar** [comment]
Can the filter bar **not** respond to vertical scrolling?

**Comment by Meberem** [comment]
> Can the filter bar not respond to vertical scrolling?
What does that mean?

**Comment by bzaar** [comment]
> > Can the filter bar not respond to vertical scrolling?
> 
> What does that mean?

Sorry, that does sound very ambiguous. What I mean is when you put your finger down inside the filter bar area and move it vertically, the filter bar should not scroll vertically (as in master), only horizontally (if there is any horizontal component in your movement). Does this make more sense now?

**Comment by bzaar** [comment]
If it's too difficult to implement or adds more complexity than it solves, please don't bother. It was just a bit unexpected that you could scroll results by grabbing the filters. But now that I think of it, it's not too terrible and sort of fits the idea of results and filters scrolling together.

**Comment by Meberem** [comment]
It looks like it would be possible but Chrome is advising that it would be a bad idea from a performance point of view so I would say best to avoid it

**Comment by bzaar** [comment]
Thanks a lot for this! Works perfectly!

**Pull request merged**
