### PR TITLE
Search filters

### PR DESCRIPTION
**Pull request by Meberem**
image
image
image

### CODE REVIEW

**Comment by bzaar** [comment]
Looks good! Can you publish please?

**Comment by Meberem** [comment]
Have just done that now 😊

**Comment by bzaar** [comment]
I see the new UI but filters are not getting applied. Have you updated the
API?

**Comment by Meberem** [comment]
I have raised a PR for that https://bitbucket.org/concat/gramdict.ru.api/pull-requests/2/accept-string-symbol-parameter-add/diff

**Comment by bzaar** [comment]
Can you publish the API from your branch too?

**Comment by bzaar** [comment]
On the UI side, I would like the up/down arrow to appear only in search
mode.

**Comment by Meberem** [comment]
I have pushed the API and updated the UI to hide the arrows until a search has been performed.

The filters appear to work expect for http://api.gramdict.ru/v1/search/*?pagesize=210&pagenum=0&symbol=мн.от where nothing is returned. I assume this is because the symbol is not right. Would you be able to tell me exactly what it should be?

**Comment by bzaar** [comment]
Thanks!  Looks like your last changes broke the italics in мн. _от_?

**Comment by Meberem** [comment]
Sorry just republishing now, I was experimenting to see what would have caused the 0 results, should be fixed now

**Comment by bzaar** [comment]
Great, thanks!  I've had a look and it works as expected except for a few
minot points:

1. When I tap randomly on the filters sometimes it takes a filter 3-6
seconds to change state. Usually this happens just before results are
updated. I understand that JavaScript is single-threaded so I guess a pause
is to be expected when it's parsing the results. I'm just bringing this to
your attention in case you can think of a way to alleviate the undesired
pause. Maybe make pagesize smaller on monile devices?

2. When the down arrow is clicked, it shows grid lines momentarily - see
the attached screen shot. Could the transition be smoother?

3. Can the search input box width be more flexible to accommodate for the
appearing/disappearing button? Say, fill-available; min-width:3rem;
max-width: 7rem.

4. The "мн. _от_" filter should be sent down to the api as `symbol=мн.
_от_` i.e. with the underscores just like Markdown.

**Comment by Meberem** [comment]
1. Yes this is kind of a tricky one CSV parsing is expensive and this could be an issue on mobile devices. There is the idea of a service worker which _might_ be benefical in this scenario however if the API was to return JSON then the page would have to do virtually no work at all.

2. I can't seem to see the screenshot or see it in my browser but I have added some CSS to remove any and all grid lines

3. I have added some styles so it starts off wider then shrinks when the button appears. Is that what you mean.

image
image

4. I have made that change

**Comment by bzaar** [comment]
Thanks! Can you publish your recent changes?

**Comment by Meberem** [comment]
published

**Comment by bzaar** [comment]
It looks much better without the grid lines, thanks! Here is what it looked like before:

https://photos.app.goo.gl/8kyr7vHvSUpUwTZV9

**Comment by bzaar** [comment]
Currently, "Содержание" gets wrapped over in the menu bar:

https://photos.app.goo.gl/kBYWVe5AExEgLK7T7

Can it be beside the search box?

**Comment by bzaar** [comment]
That's an interesting point about JSON. Its just CSV seems like the most concise representation of the data that we are dealing with. 

Meanwhile, can we try this one-line fix, something along these lines (or line, even!):

let pagesize = mobile ? 20 : 210;

**Comment by Meberem** [comment]
Oh that does look pretty awful!
What device is that? I have tried replicating with Chrome dev tools but I can't quite get that, I will increase the width to prevent that though.
I will add something for that, it will have to be done via media queries though. 
With compression the additional overhead will be minimal

**Comment by Meberem** [comment]
I have pushed those changes to live, I am able to see 20 results when I am simulating a mobile device and I have the extra space should prevent the issue you are seeing with Содержание being pushed onto a new line

**Comment by bzaar** [comment]
That looks much better now, thanks! An the unresponsiveness when clicking on filters is gone too.

**Comment by bzaar** [comment]
In the filter area, I think there is a bit too much padding at the bottom
and too little at the top. I think it would look better with a consistent
padding of about 1ex all around.

https://photos.app.goo.gl/XuvT4q76WueXoqq36

**Comment by bzaar** [comment]
See the original mock-up:

**Comment by Meberem** [comment]
Sorry for some reason I'm really struggling to see the blacks on my monitor, I have pushed up the changes
image

**Pull request merged**
